import { Match, Standing, PlayerStat } from './types';

export const TEAMS = [
  'Rangpur',
  'Sylhet',
  'Khulna',
  'Barishal',
  'Dhaka',
  'Rajshahi',
  'Chattogram',
  'Mymensingh',
];

export const MATCHES: Match[] = [
  {
    id: '1',
    date: '16 July 2026, Thursday',
    time: '4:00 PM',
    homeTeam: 'Rangpur',
    awayTeam: 'Sylhet',
    status: 'FULL_TIME',
    homeScore: 1,
    awayScore: 0,
    homeGoals: [{ playerName: 'Chayan (OG)', count: 1 }],
    motm: 'Sakib',
  },
  {
    id: '2',
    date: '17 July 2026, Friday',
    time: '3:30 PM',
    homeTeam: 'Khulna',
    awayTeam: 'Barishal',
    status: 'FULL_TIME',
    homeScore: 5,
    awayScore: 0,
    homeGoals: [
      { playerName: 'Jubayer', count: 2 },
      { playerName: 'Biplob', count: 1 },
      { playerName: 'Hussain', count: 1 },
      { playerName: 'Sumon', count: 1 }
    ],
    motm: 'Jubayer',
  },
  {
    id: '3',
    date: '17 July 2026, Friday',
    time: '4:30 PM',
    homeTeam: 'Mymensingh',
    awayTeam: 'Rajshahi',
    status: 'FULL_TIME',
    homeScore: 0,
    awayScore: 2,
    awayGoals: [
      { playerName: 'Sakib', count: 1 },
      { playerName: 'Jahir (OG)', count: 1 }
    ],
    motm: 'Sakib',
  },
  {
    id: '4',
    date: '19 July 2026, Sunday',
    time: '3:30 PM',
    homeTeam: 'Sylhet',
    awayTeam: 'Barishal',
    status: 'FULL_TIME',
    homeScore: 1,
    awayScore: 0,
    homeGoals: [{ playerName: 'Tofayel', count: 1 }],
    motm: 'Tofayel',
  },
  {
    id: '5',
    date: '19 July 2026, Sunday',
    time: '4:30 PM',
    homeTeam: 'Dhaka',
    awayTeam: 'Rajshahi',
    status: 'FULL_TIME',
    homeScore: 1,
    awayScore: 1,
    homeGoals: [{ playerName: 'Raja', count: 1 }],
    awayGoals: [{ playerName: 'Naeem', count: 1 }],
    motm: 'Raja',
  },
  {
    id: '6',
    date: '20 July 2026, Monday',
    time: '3:30 PM',
    homeTeam: 'Rangpur',
    awayTeam: 'Khulna',
    status: 'POSTPONED',
  },
  {
    id: '7',
    date: '20 July 2026, Monday',
    time: '4:30 PM',
    homeTeam: 'Chattogram',
    awayTeam: 'Mymensingh',
    status: 'POSTPONED',
  },
  {
    id: '8',
    date: '21 July 2026, Tuesday',
    time: '3:30 PM',
    homeTeam: 'Rangpur',
    awayTeam: 'Barishal',
    status: 'FULL_TIME',
    homeScore: 2,
    awayScore: 0,
    homeGoals: [
      { playerName: 'Sagor', count: 1 },
      { playerName: 'Sharif', count: 1 }
    ],
    motm: 'Sagor',
  },
  {
    id: '9',
    date: '21 July 2026, Tuesday',
    time: '4:30 PM',
    homeTeam: 'Sylhet',
    awayTeam: 'Khulna',
    status: 'FULL_TIME',
    homeScore: 0,
    awayScore: 1,
    awayGoals: [{ playerName: 'Biplob', count: 1 }],
    motm: 'Biplob',
  },
  {
    id: '10',
    date: '22 July 2026, Wednesday',
    time: '3:30 PM',
    homeTeam: 'Mymensingh',
    awayTeam: 'Dhaka',
    status: 'POSTPONED',
  },
  {
    id: '11',
    date: '22 July 2026, Wednesday',
    time: '4:30 PM',
    homeTeam: 'Chattogram',
    awayTeam: 'Rajshahi',
    status: 'POSTPONED',
  },
  {
    id: '12',
    date: '23 July 2026, Thursday',
    time: '4:30 PM',
    homeTeam: 'Dhaka',
    awayTeam: 'Chattogram',
    status: 'POSTPONED',
  },
  {
    id: '13',
    date: 'TBD',
    time: 'TBD',
    homeTeam: 'TBD',
    awayTeam: 'TBD',
    status: 'SCHEDULED',
  },
  {
    id: '14',
    date: 'TBD',
    time: 'TBD',
    homeTeam: 'TBD',
    awayTeam: 'TBD',
    status: 'SCHEDULED',
  },
  {
    id: '15',
    date: 'TBD',
    time: 'TBD',
    homeTeam: 'TBD',
    awayTeam: 'TBD',
    status: 'SCHEDULED',
  },
];

export const STANDINGS: Standing[] = [
  { team: 'Rangpur', played: 2, won: 2, drawn: 0, lost: 0, goalsFor: 3, goalsAgainst: 0, goalDifference: 3, points: 6, group: 'A' },
  { team: 'Sylhet', played: 3, won: 1, drawn: 0, lost: 2, goalsFor: 1, goalsAgainst: 2, goalDifference: -1, points: 3, group: 'A' },
  { team: 'Khulna', played: 2, won: 2, drawn: 0, lost: 0, goalsFor: 6, goalsAgainst: 0, goalDifference: 6, points: 6, group: 'A' },
  { team: 'Barishal', played: 3, won: 0, drawn: 0, lost: 3, goalsFor: 0, goalsAgainst: 8, goalDifference: -8, points: 0, group: 'A' },
  { team: 'Dhaka', played: 1, won: 0, drawn: 1, lost: 0, goalsFor: 1, goalsAgainst: 1, goalDifference: 0, points: 1, group: 'B' },
  { team: 'Rajshahi', played: 2, won: 1, drawn: 1, lost: 0, goalsFor: 3, goalsAgainst: 1, goalDifference: 2, points: 4, group: 'B' },
  { team: 'Chattogram', played: 0, won: 0, drawn: 0, lost: 0, goalsFor: 0, goalsAgainst: 0, goalDifference: 0, points: 0, group: 'B' },
  { team: 'Mymensingh', played: 1, won: 0, drawn: 0, lost: 1, goalsFor: 0, goalsAgainst: 2, goalDifference: -2, points: 0, group: 'B' },
];

export const PLAYER_STATS: PlayerStat[] = [
  { name: 'Sakib', team: 'Rangpur', goals: 0, motms: 1 },
  { name: 'Jubayer', team: 'Khulna', goals: 2, motms: 1 },
  { name: 'Sakib', team: 'Rajshahi', goals: 1, motms: 1 },
  { name: 'Tofayel', team: 'Sylhet', goals: 1, motms: 1 },
  { name: 'Raja', team: 'Dhaka', goals: 1, motms: 1 },
  { name: 'Biplob', team: 'Khulna', goals: 2, motms: 1 },
  { name: 'Sagor', team: 'Rangpur', goals: 1, motms: 1 },
  { name: 'Sharif', team: 'Rangpur', goals: 1, motms: 0 },
  { name: 'Naeem', team: 'Rajshahi', goals: 1, motms: 0 },
  { name: 'Hussain', team: 'Khulna', goals: 1, motms: 0 },
  { name: 'Sumon', team: 'Khulna', goals: 1, motms: 0 }
];
