import { Match, Standing, PlayerStat } from './types';

export const TEAMS = [
  'Rangpur',
  'Sylhet',
  'Khulna',
  'Barishal',
  'Dhaka',
  'Rajshahi',
  'Chattogram',
  'Mymensingh',
];

export const MATCHES: Match[] = [
  {
    id: '1',
    date: '16 July 2026, Thursday',
    time: '4:00 PM',
    homeTeam: 'Rangpur',
    awayTeam: 'Sylhet',
    status: 'FULL_TIME',
    homeScore: 1,
    awayScore: 0,
    homeGoals: [{ playerName: 'Sagor (OG)', count: 1 }],
    motm: 'Sakib',
  },
  {
    id: '2',
    date: '17 July 2026, Friday',
    time: '3:30 PM',
    homeTeam: 'Khulna',
    awayTeam: 'Barishal',
    status: 'FULL_TIME',
    homeScore: 5,
    awayScore: 0,
    motm: 'Jubayer',
  },
  {
    id: '3',
    date: '17 July 2026, Friday',
    time: '4:30 PM',
    homeTeam: 'Mymensingh',
    awayTeam: 'Rajshahi',
    status: 'FULL_TIME',
    homeScore: 0,
    awayScore: 2,
    awayGoals: [
      { playerName: 'Sakib', count: 1 },
      { playerName: 'Jahir (OG)', count: 1 }
    ],
    motm: 'Sakib',
  },
  {
    id: '4',
    date: '19 July 2026, Sunday',
    time: '3:30 PM',
    homeTeam: 'Sylhet',
    awayTeam: 'Barishal',
    status: 'SCHEDULED',
  },
  {
    id: '5',
    date: '19 July 2026, Sunday',
    time: '4:30 PM',
    homeTeam: 'Dhaka',
    awayTeam: 'Rajshahi',
    status: 'SCHEDULED',
  },
  {
    id: '6',
    date: '20 July 2026, Monday',
    time: '3:30 PM',
    homeTeam: 'Rangpur',
    awayTeam: 'Khulna',
    status: 'SCHEDULED',
  },
  {
    id: '7',
    date: '20 July 2026, Monday',
    time: '4:30 PM',
    homeTeam: 'Chattogram',
    awayTeam: 'Mymensingh',
    status: 'SCHEDULED',
  },
  {
    id: '8',
    date: '21 July 2026, Tuesday',
    time: '3:30 PM',
    homeTeam: 'Rangpur',
    awayTeam: 'Barishal',
    status: 'SCHEDULED',
  },
  {
    id: '9',
    date: '21 July 2026, Tuesday',
    time: '4:30 PM',
    homeTeam: 'Sylhet',
    awayTeam: 'Khulna',
    status: 'SCHEDULED',
  },
  {
    id: '10',
    date: '22 July 2026, Wednesday',
    time: '3:30 PM',
    homeTeam: 'Mymensingh',
    awayTeam: 'Dhaka',
    status: 'SCHEDULED',
  },
  {
    id: '11',
    date: '22 July 2026, Wednesday',
    time: '4:30 PM',
    homeTeam: 'Chattogram',
    awayTeam: 'Rajshahi',
    status: 'SCHEDULED',
  },
  {
    id: '12',
    date: '23 July 2026, Thursday',
    time: '4:30 PM',
    homeTeam: 'Dhaka',
    awayTeam: 'Chattogram',
    status: 'SCHEDULED',
  },
  {
    id: '13',
    date: 'TBD',
    time: 'TBD',
    homeTeam: 'TBD',
    awayTeam: 'TBD',
    status: 'SCHEDULED',
  },
  {
    id: '14',
    date: 'TBD',
    time: 'TBD',
    homeTeam: 'TBD',
    awayTeam: 'TBD',
    status: 'SCHEDULED',
  },
  {
    id: '15',
    date: 'TBD',
    time: 'TBD',
    homeTeam: 'TBD',
    awayTeam: 'TBD',
    status: 'SCHEDULED',
  },
];

export const STANDINGS: Standing[] = [
  { team: 'Rangpur', played: 1, won: 1, drawn: 0, lost: 0, goalsFor: 1, goalsAgainst: 0, goalDifference: 1, points: 3, group: 'A' },
  { team: 'Sylhet', played: 1, won: 0, drawn: 0, lost: 1, goalsFor: 0, goalsAgainst: 1, goalDifference: -1, points: 0, group: 'A' },
  { team: 'Khulna', played: 1, won: 1, drawn: 0, lost: 0, goalsFor: 5, goalsAgainst: 0, goalDifference: 5, points: 3, group: 'A' },
  { team: 'Barishal', played: 1, won: 0, drawn: 0, lost: 1, goalsFor: 0, goalsAgainst: 5, goalDifference: -5, points: 0, group: 'A' },
  { team: 'Dhaka', played: 0, won: 0, drawn: 0, lost: 0, goalsFor: 0, goalsAgainst: 0, goalDifference: 0, points: 0, group: 'B' },
  { team: 'Rajshahi', played: 1, won: 1, drawn: 0, lost: 0, goalsFor: 2, goalsAgainst: 0, goalDifference: 2, points: 3, group: 'B' },
  { team: 'Chattogram', played: 0, won: 0, drawn: 0, lost: 0, goalsFor: 0, goalsAgainst: 0, goalDifference: 0, points: 0, group: 'B' },
  { team: 'Mymensingh', played: 1, won: 0, drawn: 0, lost: 1, goalsFor: 0, goalsAgainst: 2, goalDifference: -2, points: 0, group: 'B' },
];

export const PLAYER_STATS: PlayerStat[] = [
  { name: 'Sakib', team: 'Rangpur', goals: 0, motms: 1 },
  { name: 'Jubayer', team: 'Khulna', goals: 0, motms: 1 },
  { name: 'Sakib', team: 'Rajshahi', goals: 1, motms: 1 }
];
